### ISSUE TITLE
experiment with async GET calls

### ISSUE THREAD

**Issue by lsoares** [refactors/github-profile-widget#19]
http://stackoverflow.com/a/962920/819651

**Comment by hacdias** [comment]
Nothing done because it would need third party modules.

**Comment by lsoares** [comment]
What about async curl?

No dia domingo, 5 de julho de 2015, Henrique Dias notifications@github.com
escreveu:

> Closed #19 https://github.com/refactors/github-profile-widget/issues/19.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/refactors/github-profile-widget/issues/19#event-348071984
> .

## 

---

Luís Soares
luissoares.com

**Comment by hacdias** [comment]
It needs third party modules.

**Comment by lsoares** [comment]
If it's available in many places... We could give it a try

No dia domingo, 5 de julho de 2015, Henrique Dias notifications@github.com
escreveu:

> It needs third party modules.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/refactors/github-profile-widget/issues/19#issuecomment-118642551
> .

## 

---

Luís Soares
luissoares.com
