### ISSUE TITLE
Remove "Network: true"

### ISSUE THREAD

**Issue by halkeye** [refactors/github-profile-widget#23]
Why is this a network activate only module?

**Comment by hacdias** [comment]
Isn't the network var used to tell that the plugin works with Network installations? It used to be. I may be mistaken. The last time I tested, the plugin worked on non-network installations.

**Comment by halkeye** [comment]
I'm running multi site install. Network: true only let me network activate (which afaik, means every site has it enabled) compared to each site being able to chose to enable it or not.

**Comment by halkeye** [comment]
I wasn't going to do a PR for this as I wasn't sure what advantages network activate has

**Comment by hacdias** [comment]
Hi @halkeye 

Thank you for discussing this. There's no advantage in having it enabled on every site. If you can make a PR, I'll thank and merge it as soon as possible. 

Happy New Year!
